### ISSUE TITLE
Add capability to play same sound as a new instance

### ISSUE THREAD

**Issue by ianmcgregor** [Stinkstudios/sono#11]
Need to be able to play the same sound multiple times overlaid on top of instances of it already playing. E.g button rollovers, shoot/explosion effect etc etc. Should be pooled to minimise number of instances created.

**Comment by craigbrett17** [comment]
@ianmcgregor: I see that this has been implemented and that there's some kind of example somewhere, but I can't find it when I look. How would I go about doing this? I see you put multiplay in the sound config object. But then what?

My particular example is playing the same sound but from different panned locations. Would I sono.get(id), then add a panner effect and set that to the place I want to play it for each one? 

Or am I not understanding the correct use of this feature?
