### ISSUE TITLE
'ended' doesn't get fired when loop is true

### ISSUE THREAD

**Issue by amelierosser** [Stinkstudios/sono#24]
I just tested the following case where `ended` doesn't get fired when looping a sound.

```
const sound = sono.load({
  src: [`/assets/audio/dnb-loop.${getFormat()}`],
  loop: true
});

sound.on('ended', () => {
  console.log('ended');
});

sound.play();
```

I know the sound doesn't theoretically end when looping. But it would be really useful to have a callback regardless if say we wanted to know when the sound has played X times.

**Comment by ianmcgregor** [comment]
Hey Amelie, yes this is a Web Audio thing.

The only way to detect looping afaik would be to run a `requestAnimationFrame` loop and monitor the currentTime which wouldn't be 100% accurate and also introduce a perf penalty in running the raf.

Would be useful to be able to do something like `sound.on('loop', fn)`. Could maybe experiment with adding the raf only when the listener is added.

**Comment by amelierosser** [comment]
Hey Ian,

Ahh I see, I don't see this as a bug then. Work arounds can be done outside of sono to achieve the desired behaviour.
