### ISSUE TITLE
currentTime increases after each successive playback when looping

### ISSUE THREAD

**Issue by amelierosser** [Stinkstudios/sono#25]
I observed that the currentTime doesn't reset to 0 after a play when loop set to true.

```
const sound = sono.load({
  src: [`/assets/audio/dnb-loop.${getFormat()}`],
  loop: true
});

sound.on('ended', () => {
  console.log('ended');
});

sound.play();

function update() {
  requestAnimationFrame(update);
  console.log(sound.currentTime, '/', sound.duration);
}

update();
```

The currentTime increases after every playback. See attached:

![screen shot 2017-05-11 at 10 15 28](https://cloud.githubusercontent.com/assets/435118/25942154/ef8925a0-3633-11e7-9a05-b7a1698f780a.png)

**Comment by ianmcgregor** [comment]
Nice catch @amelierosser, was a regression. Thanks again!
