### ISSUE TITLE
Mix dry signal with Convolution Reverb

### ISSUE THREAD

**Issue by Ghorthalon** [Stinkstudios/sono#28]
When adding a sono.convolver() effect to a sound, the entire sound is convolved without an option of leaving the dry signal in tact. The convolver works, but this makes it harder to implement. Maybe add a boolean to also connect the dry signal to the output bus so you have the dry plus the convolved signal as output?

**Comment by ianmcgregor** [comment]
Hey @Ghorthalon, yes good suggestion. Would be good to have a wet/dry mix option across effects. I'll get to this when time permits. Also if you're up for it a PR would be welcome.

**Comment by ianmcgregor** [comment]
@Ghorthalon this has now been implemented. Example here: <http://stinkstudios.github.io/sono/examples/convolver.html>
