### ISSUE TITLE
Option to keep playing in background

### ISSUE THREAD

**Issue by kundralaci** [Stinkstudios/sono#32]
I don't know if it's by purpose (or me just not seeing it), but now it's not possible to keep playing in the background, and there is no option for that. It would be nice to have one, and keep playing while document's visibility goes `hidden`.

It could be as easy as adding a boolean property to the `sono` object, for which `onShown` and `onHidden` functions could branch and keep playing. (I haven't dive deep into the code, maybe it's not the most beautiful solution.)

Thank you in advice for any kind of help!

**Comment by ianmcgregor** [comment]
Added in 2.1.1. Default behaviour is still to suspend audio when the doc is hidden but you can disable it like this:

`sono.playInBackground = true`

Example of it working here: http://stinkstudios.github.io/sono/examples/background.html

**Comment by TimvanScherpenzeel** [comment]
Thank you very much for the quick implementation and the library in general, it has been a massive help in overcoming all these edge cases of the Web Audio API 👍. It has been working much better for me than Howler.js or the using the API directly in terms of cross device compatibility.

**Comment by ianmcgregor** [comment]
Thanks @TimvanScherpenzeel, that's great to hear. Please don't hesitate to get in touch in future if you find any faults or have any ideas how to improve.

**Comment by kundralaci** [comment]
Wow, thanks for the quick solution! Keep up the good work! :)
