### ISSUE TITLE
Clone buffer not working properly, creates extra copy of the sound into memory

### ISSUE THREAD

**Issue by ogomez92** [Stinkstudios/sono#44]
Hello!
we are trying to build a sound library using sono fr game development.
As you might expect, games do require the same sound or music to be loaded into multiple objects.
We tried to use cloneBuffer to get around the fact that loading the sound into memory many times would take unnecessary ram.
We are checking for the sound data when the same filename is loaded and, if it exists, create a new sound and clone a buffer, like this:

			returnObject = sono.create("");
			returnObject.data = sono.utils.cloneBuffer(found.data);

We get to the cloning stage alright, but the data from the buffer is coppied into memory thus making 2 separate coppies in ram.

Is there a way to get this same buffer on a separate sound without it taking double ram?

I would greatly appreciate this and it would help us a lot!

Thanks!!

**Comment by ogomez92** [comment]
I'm guessing that if we just made the other sound's .data the same .data from the other sound, any changes to volume, playbackRate, etc, would get cloned into the other sound, which is not what we want.

Any  hints will be greatly appreciated.

**Comment by ianmcgregor** [comment]
Hey @ogomez92 there is a built-in sound pooling feature that allows you to play the same sound many times overlapping (e.g. explosions, bullets) while minimising any object creation.

Just call play as many times as you want on the sound and it will do its thing. Have a look at the code here to see how it works: https://github.com/Stinkstudios/sono/blob/master/src/core/source/audio-source.js

**Comment by ogomez92** [comment]
Is it OK if I use audioSource.js to modify my own library instead so
that it does not create multiple objects?
I'm not sure if your library will let me apply properties to each copy
of the sound.
We are working on audiogames and each copy of the sound would need its
own volume, playbackRate, pan...

Does this make sense?

Thanks.

**Comment by ianmcgregor** [comment]
The library is open source so yes you are free to make your own modified version.

You could do `soundB = sono.create(soundA.data)` to have a new sound with the same data

**Comment by ogomez92** [comment]
thanks that is what I needed!
If you have some time, can you explain all these connction nodes etc?
Is this just for volume gain etc?

Greetings!

**Comment by ianmcgregor** [comment]
Check the docs here for other types of nodes you can add:

https://github.com/Stinkstudios/sono/blob/master/docs/effects.md

**Comment by ogomez92** [comment]
Thank you very much and for your quick response.

Cheers.

**Comment by ianmcgregor** [comment]
You're welcome!
