### ISSUE TITLE
Wrong typo

### ISSUE THREAD

**Issue by tamascsaba** [Stinkstudios/sono#51]
hi,

I found a wrong typo. I can't call remove function on SoundGroup. 

https://github.com/Stinkstudios/sono/blob/fb7d1dbde6d2c814b004710d06ca83ce695994fc/src/core/utils/sound-group.js#L26

**Comment by tamascsaba** [comment]
@ianmcgregor nice work 👍

**Comment by ianmcgregor** [comment]
Thanks @tamascsaba @andykenward v2.1.6 published
